export default {
  PRIMARY_COLOR: '#2aabb8',
  FONT_SIZE_SMALL: 9,
  FONT_SIZE_MEDIUM: 15,
  FONT_SIZE_LARGE: 21,
  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_MEDIUM: '500',
  FONT_WEIGHT_BOLD: '700',
  BACKGROUND_COLOR_LIGHT: '#f0f6f7',
  PADDING: 8,
  MARGIN: 8,
};
